from winsound import Beep
from colorama import Fore, init

import time

init(autoreset=True)

def english():
    Beep(2000, 1500)
    print(f"{Fore.RED}  WARNING : Integration may took long time to finish")
    print(f"{Fore.RED}            One Integration may took around 1 minute, depending on")
    print(f"{Fore.RED}            how complex the expression, specially if it \\frac{{u}}{{v}}\n")
    Beep(2000, 800)
    time.sleep(0.5)
    print(f"{Fore.RED}  WARNING : Some problems may use a lot of memory and CPU runtime,")
    print(f"{Fore.RED}            make sure no NOT RUN any heavy applications such as games,")
    print(f"{Fore.RED}            Adbobe Prmiere, and any CPU or RAM demanding apps\n")
    Beep(2000, 800)
    time.sleep(0.5)
    print(f"{Fore.BLUE}  INFO    : Derrivation after integration maybe not the same as ")
    print(f"{Fore.BLUE}            the base This is likely due to SymPy limitation\n")
    Beep(2000, 800)
    time.sleep(0.5)
    print(f"{Fore.BLUE}  INFO    : Some may showing \"Integral({{expr}})\" this is also ")
    print(f"{Fore.BLUE}            likely to be SymPy limitation\n")

def german():
    Beep(2000, 1500)
    print(f"{Fore.RED}  WARNUNG: Die Integration kann lange dauern, um abgeschlossen zu werden.")
    print(f"{Fore.RED}           Eine Integration kann etwa 1 Minute dauern, abhängig von")
    print(f"{Fore.RED}           wie komplex der Ausdruck ist, besonders wenn es \\frac{{u}}{{v}} enthält\n")
    Beep(2000, 800)
    time.sleep(0.5)
    print(f"{Fore.RED}  WARNUNG: Einige Probleme können viel Speicher und CPU-Zeit verwenden,")
    print(f"{Fore.RED}           stellen Sie sicher, dass Sie KEINE schweren Anwendungen ausführen, wie Spiele,")
    print(f"{Fore.RED}           Adobe Premiere und andere anspruchsvolle CPU- oder RAM-Anwendungen\n")
    Beep(2000, 800)
    time.sleep(0.5)
    print(f"{Fore.BLUE}  INFO: Die Ableitung nach der Integration ist möglicherweise nicht die gleiche wie")
    print(f"{Fore.BLUE}         die Basis. Dies ist wahrscheinlich auf die Beschränkungen von SymPy zurückzuführen\n")
    Beep(2000, 800)
    time.sleep(0.5)
    print(f"{Fore.BLUE}  INFO: Einige Ausdrücke können \"Integral({{expr}})\" anzeigen. Dies ist ebenfalls")
    print(f"{Fore.BLUE}         wahrscheinlich auf die Beschränkungen von SymPy zurückzuführen\n")

def dutch():
    Beep(2000, 1500)
    print(f"{Fore.RED}  WAARSCHUWING: Integratie kan lang duren om te voltooien.")
    print(f"{Fore.RED}                Eén integratie kan ongeveer 1 minuut duren, afhankelijk van")
    print(f"{Fore.RED}                hoe complex de expressie is, vooral als het \\frac{{u}}{{v}} bevat\n")
    Beep(2000, 800)
    time.sleep(0.5)
    print(f"{Fore.RED}  WAARSCHUWING: Sommige problemen kunnen veel geheugen en CPU-tijd gebruiken,")
    print(f"{Fore.RED}                zorg ervoor dat u GEEN zware toepassingen uitvoert, zoals games,")
    print(f"{Fore.RED}                Adobe Premiere en andere CPU- of RAM-intensieve apps\n")
    Beep(2000, 800)
    time.sleep(0.5)
    print(f"{Fore.BLUE}  INFORMATIE: Afgeleiden na integratie kunnen anders zijn dan")
    print(f"{Fore.BLUE}              de basis. Dit is waarschijnlijk te wijten aan beperkingen van SymPy\n")
    Beep(2000, 800)
    time.sleep(0.5)
    print(f"{Fore.BLUE}  INFORMATIE: Sommige uitdrukkingen kunnen \"Integral({{expr}})\" tonen. Dit is ook")
    print(f"{Fore.BLUE}              waarschijnlijk te wijten aan beperkingen van SymPy\n")

def aceh():
    Beep(2000, 1500)
    print(f"{Fore.RED}  MEUNTOH : Integrasi peurboh sikit lawan wakatoo lambé jang. Seuk beungeuh meunyoe, pado ")
    print(f"{Fore.RED}            peulawih meunyoe mungkin beungeuh seuk 1 menit, badeungon ")
    print(f"{Fore.RED}            pirhiasan haba geutanyo, meunyoe teupot su salah satoo \\frac{{u}}{{v}}\n")
    Beep(2000, 800)
    time.sleep(0.5)
    print(f"{Fore.RED}  MEUNTOH : Beungeuh problem dapat meusabot daya memory dan wakatoo CPU nyoe,")
    print(f"{Fore.RED}            pastikan lam kaboh meureun aplikasi kawon seupay meupi geutanyo,")
    print(f"{Fore.RED}            peule gam nyabôh, Adobe Premiere, dan aplikasi CPU atau RAM nan reuba\n")
    Beep(2000, 800)
    time.sleep(0.5)
    print(f"{Fore.BLUE}  INPÔ : Meunyoe pasca integrasi keutamoe neubé badeubah bukan geutanyo base. ")
    print(f"{Fore.BLUE}         Ie aya geutanyo seupay menunjukkan \"Integral({{expr}})\" ini o ieu dapeutae geutanyo")
    print(f"{Fore.BLUE}         SymPy\n")
    Beep(2000, 800)
    time.sleep(0.5)
    print(f"{Fore.BLUE}  INPÔ : Meunyoe pasca integrasi keutamoe meunyoe panyaweing \"Integral({{expr}})\" ini o ieu")
    print(f"{Fore.BLUE}         dapeutae geutanyo o bawaan ku SymPy\n")
